namespace GrandSluggers.Sim;

public static partial class HowToPlay
{
    // Copy belongs to the book. The lesson runner owns the actions and verdicts.
    sealed record TutorialCopy(string Title, string Goal, string Setup, string Pad, string Keys);

    static TutorialCopy? RemainingTutorial(string id, string profile = "shipped") => id switch
    {
        // The field's lessons (F8-c): one per hazard pattern and per ground that changes the ball, each at its own park.
        "T-H01" => new("Field on the ice", "Field a ground ball on Crystal's ice outfield.",
            "At Crystal Rink a grounder runs and skids farther on the ice, and your fielder is slow to stop. Get there early.",
            "Steer the fielder to the ball with the stick; slow down early. Position secures it automatically.",
            "Steer the fielder to the ball with WASD; slow down early. Space secures it."),
        "T-H02" => new("Go around the freezer", "Catch the fly without running through a freezer.",
            "At Crystal Rink a fielder who runs through a freezer slows for 3 seconds. Bend your run around it.",
            "Steer around the frozen disc with the stick, meet the ball as it comes down.",
            "Steer around the frozen disc with WASD, then tap Space as the ball comes down."),
        "T-H03" => new("Read the warp can", "Take the ball after it comes out of another can.",
            "At Funfair Park a ball that goes into a warp can pops out of another. Wait for it, then go get it.",
            "Hold your spot until the ball comes out, then steer to it with the stick. Position secures it automatically.",
            "Hold your spot until the ball comes out, then steer to it with WASD. Space secures it."),
        "T-H04" => new("Play the tree", "Take the ball after it bounces off a tree.",
            "At Canopy Yard the trees are in play: a ball comes back off them. Wait for the bounce, then go get it.",
            "Hold your spot until the ball bounces back, then steer to it with the stick. Position secures it automatically.",
            "Hold your spot until the ball bounces back, then steer to it with WASD. Space secures it."),
        "T-H05" => new("Beat the train", "Catch the fly with the train running along the wall.",
            "At Funfair Park the train runs along the wall. It is solid: a ball bounces off it.",
            "Steer under the fly with the stick as it comes down.",
            "Steer under the fly with WASD and tap Space as it comes down."),
        "T-H06" => new("Hit the billboard", "Put a ball under a billboard for a star.",
            "At Rooftop City a ball that passes under a billboard pays the batting team a star.",
            "Aim with the stick and swing with RT.",
            "Aim with WASD and swing with Space."),
        "T-H07" => new("Climb the wall", "Rob a ball at the wall with a Clamber fielder.",
            "At Canopy Yard a Clamber fielder climbs the vine wall to rob a ball clearing the fence.",
            "Steer to the wall with the stick and press North to climb.",
            "Steer to the wall with WASD and press F to climb."),
        "T-G04" => new("Build a 1–1 count", "Pitch a ball, then a called strike to make the count 1–1.",
            "The batter takes both pitches. Move left to the rubber's edge for the ball, then recenter for the strike. The count stays visible.",
            "During SET, walk left to the rubber's edge; release the stick and tap RT. Next pitch, stick down resets; RT throws a strike.",
            "During SET, walk left to the rubber's edge; release the key and tap Space. Next pitch, S resets; Space throws a strike."),
        "T-G04-F" => new("Hit foul, then fair", "Hit a foul ball for a strike, then put the next pitch fair.",
            "The CPU throws ordinary strikes. Swing well early to pull the first ball past the line. Time the next swing for fair contact.",
            "Stay centered in SET. Tap RT well early. Next pitch, time RT for fair contact.",
            "Stay centered in SET. Tap Space well early. Next pitch, time Space for fair contact."),
        "T-G04-H" => new("Finish the half inning", "Throw a called third strike for the third out and change sides.",
            "Two outs, two strikes. The CPU takes. Your third strike ends the top half and resets the out count for the bottom half.",
            "Keep the pitch centered and tap RT. Watch the third out change sides.",
            "Keep the pitch centered and tap Space. Watch the third out change sides."),
        "T-P07" => new("Replace a tired pitcher", "Replace the tired starter with a fresh arm.",
            "The starter is tired. Open the ordinary pitcher picker and choose a fielder to take the mound.",
            "Start → Arrange defense. Stick inspects stats, ARM and chemistry. South picks two positions to swap. West quick-swaps your focus to P; East cancels / closes.",
            "R opens Arrange defense. WASD / hover inspects stats, ARM and chemistry. Space / click picks two positions to swap. R quick-swaps your focus to P; G cancels / closes."),
        "T-G01-S" => new("Rearrange the defense", "Trade your shortstop and center fielder before the pitch.",
            "You field in SET with the bases empty. Open Arrange defense, read both cards, then trade SS and CF. Leave the pitcher alone.",
            "Start → Arrange defense. Stick to SS, South picks; stick to CF, South trades them. East cancels a pick.",
            "R opens Arrange defense. WASD / hover to SS, Space / click picks; then CF trades them. G cancels a pick."),
        "T-G01-SA" => new("Rearrange the away defense", "As the away team, trade your first baseman and left fielder.",
            "Bottom of the first: your away nine fields in SET. Open Arrange defense, read both cards, then trade 1B and LF. Leave the pitcher alone.",
            "Start → Arrange defense. Stick to 1B, South picks; stick to LF, South trades them. East cancels a pick.",
            "R opens Arrange defense. WASD / hover to 1B, Space / click picks; then LF trades them. G cancels a pick."),
        "T-P08" => new("Check the runner at first", "Throw to first before starting a pitch charge. Charging first, then stepping off, is a balk.",
            "A runner is on first and ready to break. Select first and throw from the rubber. A runner who stays on the bag is safe.",
            "During SET, Right stick Right selects first. Tap South to make the pickoff throw.",
            "During SET, 1 selects first. Tap Space to make the pickoff throw."),
        "T-F07" => new("Throw through the cutoff", "Feed the cutoff and send the relay to home plate.",
            "Collect the fly, arm home and feed the cutoff. The receiver waits for your second throw command. Press again near the catch.",
            "Right stick Down arms home; RB feeds the cutoff. Tap RT again as the receiver catches.",
            "4 arms home; X feeds the cutoff. Tap Space again as the receiver catches."),
        "T-F08" => new("Queue the next throw", "Queue the onward throw just before the cutoff receives the ball.",
            "Arm home and feed the cutoff. Press throw during the final moment before reception to queue the next leg.",
            "Right stick Down arms home; RB feeds the cutoff. Tap South just before the receiver catches.",
            "4 arms home; X feeds the cutoff. Tap Space just before the receiver catches."),
        "T-F08-R" => new("Retarget a queued throw", "Queue third, then change the queued destination to home before reception.",
            "Feed the cutoff with third selected. Queue the onward throw near the catch, then select home before the receiver gets it.",
            "Right stick Left, then LB. Tap South near reception, then Right stick Down before the catch.",
            "3, then X. Tap Space near reception, then 4 before the catch."),
        "T-F08-C" => new("Cancel a queued throw", "Queue home, cancel before the catch, and keep the ball at the receiver.",
            "Feed the cutoff and queue home just before reception. Cancel before the catch so the receiver keeps the ball.",
            "Right stick Down, then LB. Tap South near reception; East cancels before the catch.",
            "4, then X. Tap Space near reception; period cancels before the catch."),
        "T-G02" => new("Throw with chemistry", "Feed the cutoff with a good-chemistry pair.",
            "Moss and Vine are paired for this throw. Collect the fly and feed the cutoff; the live throw must receive their chemistry boost.",
            "Right stick Down arms home. Collect the fly, then RB feeds the cutoff.",
            "4 arms home. Collect the fly, then X feeds the cutoff."),
        "T-F09" => new("Chase a wall carom", "Take over and scoop the loose ball after it rebounds from the wall.",
            "Watch the wall bounce. Steer your glove toward the moving ball and collect it yourself; letting the helper finish does not count.",
            "After the wall bounce, use the left stick to chase the live ball and scoop it.",
            "After the wall bounce, use WASD to chase the live ball and scoop it."),
        "T-F09-B" => new("Recover a bobbled ball", "Take over after the bobble and scoop the loose ball yourself.",
            "The helper bobbles an ordinary grounder. After the error, steer toward the loose ball and keep control through the scoop.",
            "Wait for the bobble, then use the left stick to chase and collect the loose ball.",
            "Wait for the bobble, then use WASD to chase and collect the loose ball."),
        "T-F10" => new("Throw to the arriving cover", "Throw to first while its covering teammate is still arriving.",
            "The first baseman fields away from the bag. Throw to first before the covering second baseman gets there; watch the reception wait for the cover.",
            "Collect the grounder. Right stick Right selects first; RT throws immediately.",
            "Collect the grounder. 1 selects first; Space throws immediately."),
        "T-F11" => new("Return a wall carom", "Collect the wall rebound and throw to the receiver at third.",
            "Let the ball rebound off Harbor's wall. Your glove can collect it with help; you must choose third and make the return throw.",
            "After the rebound, collect the ball. Right stick Left selects third; RT throws.",
            "After the rebound, collect the ball. 3 selects third; Space throws."),
        "T-F12" => new("Buddy jump at the wall", "Jump with a partner to rob a home run at the wall.",
            "Both outfielders must reach the wall spot together. Jump with the ball directly overhead; a late partner cannot boost you.",
            "Let the gloves reach the wall play. Press North in the jump window.",
            "Let the gloves reach the wall play. Press F in the jump window."),
        "T-F13" => new("Run with Ball Dash", "Carry the ball with a fielder who has Ball Dash.",
            "Ball Dash changes movement while this fielder securely holds the ball. Take control after collecting it.",
            "Collect the ball, then push the left stick fully to run with it.",
            "Collect the ball, then use WASD to run with it."),
        "T-F14" => new("Make a Snap Throw", "Feed a clean throw to a Snap Throw receiver and send it home.",
            "Snap Throw shortens this receiver's release after a clean catch. Feed the cutoff and command the onward throw near the catch.",
            "Right stick Down arms home; RB feeds the cutoff. RT near the catch sends the next leg.",
            "4 arms home; X feeds the cutoff. Space near the catch sends the next leg."),
        "T-F15" => new("Fire a Laser Throw", "Use a Laser fielder to send the ball home.",
            "The runner threatens home. Collect the ball with the Laser fielder and make the throw to the catcher.",
            "Collect the ball. Right stick Down selects home; RT throws.",
            "Collect the ball. 4 selects home; Space throws."),
        "T-R01" => new("Send, hold and return", "Send the runner from second toward third, halt, then return safely to second.",
            "Select the runner on second. Move off the bag, halt that runner, then send them back. Finish by reaching second again.",
            "Right stick Up selects second. LB sends; D-pad Up halts; RB returns.",
            "2 selects second. A sends toward third; A + slash halts. W returns to second."),
        "T-R02" => new("Send and return everyone", "Send both runners off their bags, then return them safely to their starting bags.",
            "Runners start on second and third. Send both, then hold return. Return reverses immediately. D-pad Up halts.",
            "Hold LB to advance both runners. Then hold RB until both return to their bags.",
            "Hold comma to advance both runners. Then hold period until both return to their bags."),
        "T-R02-B" => new("Give the bag back", "Two runners on second: return your batter-runner to first, safe.",
            "A runner stays on second. Send the batter to second too. The bag is the lead runner's: return yours to first before a tag.",
            "Right stick Down selects the batter; LB sends him to second. On second, RB returns him to first.",
            "4 selects the batter; W sends him to second. On second, D or period returns him to first."),
        "T-R03" => new("Dash toward first", "Use dash to accelerate the batter-runner along the first-base path.",
            "The batter starts toward first after contact. Each press builds a short speed boost; keep tapping while the runner moves.",
            "Tap South repeatedly as the batter-runner leaves home.",
            "Tap Space repeatedly as the batter-runner leaves home."),
        "T-R04" => new("Slide toward first", "Start a slide as the batter-runner approaches first base.",
            "Wait until the runner is close to first, then press to slide. Pressing too early does not request a slide.",
            "Right stick Down selects the batter-runner. Tap West just before first base.",
            "4 selects the batter-runner. Tap F or Space just before first base."),
        "T-R05" => new("Tag up from third", "Wait for the fly catch, then send the runner from third to score.",
            "The runner starts on third. Stay on the bag until the CPU catches the fly. Then send the runner home and beat the return throw.",
            "Wait for the catch, then hold LB to send the runner from third home.",
            "Wait for the catch, then hold comma to send the runner from third home."),
        "T-R06" => new("Time a steal", "Start a steal and reach the next bag safely.",
            "Select a runner and choose when to leave. They move immediately; return if the defense can beat them.",
            "Right stick selects the runner. LB starts the steal immediately.",
            "1/2/3 selects the runner. Point with WASD or press Z to start the steal."),
        "T-R07" => new("Delay the break for home", "Steal second, then send the runner from third home during the catcher throw.",
            "Send the runner at first before release. Wait for the catcher's throw toward second, then send third home as the throw passes the mound.",
            "Right stick Right then LB sends first. Release LB; during the throw, Right stick Left then LB sends third.",
            "1 then Z sends first. During the throw, 3 selects third; S sends home."),
        "T-R08" => new("Catch a stealing runner", "Throw from the catcher to retire the stealing runner.",
            "The runner breaks during the pitch. Once the catcher has the ball, select the runner's destination and throw.",
            "Right stick Up selects second. South makes the catcher's throw.",
            "2 selects second. Space makes the catcher's throw."),
        "T-D01" => new("Force the runner at home", "Throw home before the forced runner reaches the plate.",
            "Bases are loaded. The pitcher fields the grounder. The runner from third must advance, so the catcher needs the ball at home before that runner arrives.",
            "Collect the grounder. Right stick Down selects home; RT throws.",
            "Collect the grounder. 4 selects home; Space throws."),
        "T-D07" => new("Make the third force out", "Force the runner at home for the third out and change sides.",
            "Bases are loaded with two outs. Collect the grounder and throw home before the runner arrives. The force is the third out: no run, and the teams change sides.",
            "Right stick Down selects home; RT throws after you collect the grounder.",
            "4 selects home; Space throws after you collect the grounder."),
        "T-D09" => new("Win the close tag at third", "Throw ahead of the runner and win the close tag at third.",
            "The runner from second breaks for third. Collect the grounder, throw to third, then react when the close-play icon appears.",
            "Right stick Left selects third; RT throws. At the close-play icon, press South again.",
            "3 selects third; Space throws. At the close-play icon, press Space again."),
        "T-D06" => new("Win a close play at third", "Send the runner from second and beat the close tag at third.",
            "Send the runner as the grounder starts and give them a few dash taps. Watch for the close-play icon at third, then react with one fresh press.",
            "LB sends the runner; tap South to dash. When the close-play icon appears, press South again.",
            "Comma sends the runner; tap Space to dash. When the close-play icon appears, press Space again."),
        "T-D05" => new("Finish a rundown", "Pick off first, then throw ahead to tag the trapped runner at second.",
            "The runner is ready to break from first. Check first from the mound; after the rundown starts, throw to second for the tag.",
            "During SET: Right stick Right held + RT picks off first. Then Right stick Up + RT throws to second.",
            "During SET: 1 then Space picks off first. Then 2 and Space throws to second."),
        "T-D03" => new("Choose the lead out", "Throw to second to retire the lead runner while the batter reaches first.",
            "A runner starts on first. Choose second for the force out. The batter may reach first while you retire the lead runner.",
            "Right stick Up selects second. Collect the grounder and throw with RT.",
            "2 selects second. Collect the grounder and throw with Space."),
        "T-R10" => new("Return on a fly ball", "Send the runner early, then bring them safely back to third before the catch.",
            "A fly is in the air with a runner on third. Practice correcting an early send: leave the bag, then return and stay there through the catch.",
            "Right stick Left selects third; LB sends home. Once off the bag, hold RB to return to third before the catch.",
            "3 selects third; S sends home. Once off the bag, hold period to return to third before the catch."),
        "T-R09" => new("Dash around first", "Send the batter-runner beyond first and dash through the turn toward second.",
            "A gap hit gives time to reach first. Select that runner after touching the bag, send toward second, then dash as they make the turn.",
            "At first, Right stick Down selects the batter-runner; LB sends toward second. Tap South as the runner turns beyond first.",
            "At first, 1 selects the runner; W sends toward second. Tap Space as the runner turns beyond first."),
        "T-D07-T" => new("Cancel a run with a force", "Make the third force at second after the lead runner crosses home.",
            "Two outs, runners on first and third. Collect the grounder. As the fast runner approaches home, force the slower runner at second. The lead runner crosses first, but the run will not count.",
            "As the runner nears home, Right stick Up selects second; RT throws for the third force out.",
            "As the runner nears home, 2 selects second; Space throws for the third force out."),
        "T-D07-C" => new("See a run count before a tag", "Make a nonforce third out at third after the lead runner crosses home.",
            "Two outs, runners on second and third. Collect the grounder. Throw to third as the lead runner nears home, then complete the tag. The earlier run counts.",
            "As the runner nears home, Right stick Left + RT throws to third. Press RT again when the close-play icon appears.",
            "As the runner nears home, 3 and Space throws to third. Press Space again when the close-play icon appears."),
        "T-D08" => new("Turn a triple play", "Catch the fly, then double off the runners at second and first.",
            "Two CPU runners leave early on a fly. Let the glove catch, then throw back to second and first before either runner retouches.",
            "After the catch, Right stick Up + RT throws to second. After reception, Right stick Right + RT throws to first.",
            "After the catch, 2 and Space throws to second. After reception, 1 and Space throws to first."),
        "T-D04" => new("Double off a runner", "Catch the fly, then throw to second before the runner retouches.",
            "The CPU runner leaves second early. Catch the fly and return the ball to second while they are still off the bag.",
            "Catch the fly. Right stick Up selects second; RT throws behind the runner.",
            "Catch the fly. 2 selects second; Space throws behind the runner."),
        _ => AbilityTutorial(id) ?? SpecialTutorial(id)
    };
}
