namespace GrandSluggers.Sim;

public static partial class HowToPlay
{
    // Copy belongs to the book. The lesson runner owns the actions and verdicts.
    sealed record TutorialCopy(string Title, string Goal, string Setup, string Pad, string Keys);

    static TutorialCopy? RemainingTutorial(string id) => id switch
    {
        "T-P07" => new("Replace a tired pitcher", "Replace the tired starter with a fresh arm.",
            "The starter is tired. Open the ordinary pitcher picker and choose a fielder to take the mound.",
            "Select opens the pitcher picker. Left/right picks a fielder. Select confirms.",
            "R opens the pitcher picker. A/D picks a fielder. R confirms."),
        "T-P08" => new("Check the runner at first", "Make a pickoff throw that reaches the receiver at first.",
            "A runner is on first and ready to break. Select first and throw from the rubber. A runner who stays on the bag is safe.",
            "During SET, D-pad Right selects first. Tap South to make the pickoff throw.",
            "During SET, 1 selects first. Tap Space to make the pickoff throw."),
        "T-F07" => new("Throw through the cutoff", "Get the ball to the cutoff and on to the target bag.",
            "A long throw can use an infielder as a relay. Watch the ball and the highlighted receiving glove.",
            "Collect the ball, then press LB for the cutoff. Watch the receiving glove for the next throw.",
            "Collect the ball, then press X for the cutoff. Watch the receiving glove for the next throw."),
        "T-F08" => new("Queue the next throw", "Prepare a throw before the receiver catches the ball.",
            "The receiver can remember a recent throw press. Select the destination before the catch and time your press near the handoff.",
            "D-pad selects the bag. Tap South just before the catch. RB cancels the queued throw.",
            "1/2/3/4 selects the bag. Tap Space just before the catch. Period cancels the queued throw."),
        "T-F09" => new("Recover the loose ball", "Take control and recover the ball after it gets loose.",
            "Keep watching the live ball after the failed take. Move a glove to where the ball is now.",
            "Left stick takes control. Run into the loose ball to collect it.",
            "WASD takes control. Run into the loose ball to collect it."),
        "T-F10" => new("Find the covering glove", "Send the ball to a teammate covering the target bag.",
            "A throw needs a receiver. Watch the cover move into position and send the ball to that bag.",
            "D-pad selects the covered bag. South throws when you hold the ball.",
            "1/2/3/4 selects the covered bag. Space throws when you hold the ball."),
        "T-F11" => new("Return a wall carom", "Collect the wall rebound and throw to the receiver at third.",
            "Let the ball rebound off Harbor's wall. Your glove can collect it with help; you must choose third and make the return throw.",
            "After the rebound, collect the ball. D-pad Left selects third; South throws.",
            "After the rebound, collect the ball. 3 selects third; Space throws."),
        "T-F12" => new("Buddy jump at the wall", "Jump with a partner to rob a home run at the wall.",
            "The ball is heading over the wall and a partner is nearby. Time your jump for the wall play; a standing catch does not count.",
            "Let the gloves reach the wall play. Press West in the jump window.",
            "Let the gloves reach the wall play. Press F in the jump window."),
        "T-F13" => new("Run with Ball Dash", "Carry the ball with a fielder who has Ball Dash.",
            "Ball Dash changes movement while this fielder securely holds the ball. Take control after collecting it.",
            "Collect the ball, then use the left stick to run with it.",
            "Collect the ball, then use WASD to run with it."),
        "T-F14" => new("Make a Snap Throw", "Receive a clean throw, then send the ball on with Snap Throw.",
            "This receiver has Snap Throw. Use the handoff to make the next throw quickly.",
            "Select the next bag with the D-pad. Press South as the receiver takes possession.",
            "Select the next bag with 1/2/3/4. Press Space as the receiver takes possession."),
        "T-F15" => new("Fire a Laser Throw", "Use a Laser fielder to send the ball home.",
            "The runner threatens home. Collect the ball with the Laser fielder and make the throw to the catcher.",
            "Collect the ball. D-pad Down selects home; South throws.",
            "Collect the ball. 4 selects home; Space throws."),
        "T-R01" => new("Send, hold and return", "Send the runner from second toward third, halt, then return safely to second.",
            "Select the runner on second. Move off the bag, halt that runner, then send them back. Finish by reaching second again.",
            "D-pad Up selects second. Stick left sends; left + LB + RB halts. Stick up returns.",
            "2 selects second. A sends toward third; A + slash halts. W returns to second."),
        "T-R02" => new("Send and return everyone", "Send both runners off their bags, then return them safely to their starting bags.",
            "Runners start on second and third. Send both, then hold return. The first opposite press halts; keeping it held sends them back.",
            "Hold LB to advance both runners. Then hold RB until both return to their bags.",
            "Hold comma to advance both runners. Then hold period until both return to their bags."),
        "T-R03" => new("Dash toward first", "Use dash to accelerate the batter-runner along the first-base path.",
            "The batter starts toward first after contact. Each press builds a short speed boost; keep tapping while the runner moves.",
            "Tap South repeatedly as the batter-runner leaves home.",
            "Tap Space repeatedly as the batter-runner leaves home."),
        "T-R04" => new("Slide toward first", "Start a slide as the batter-runner approaches first base.",
            "Wait until the runner is close to first, then press to slide. Pressing too early does not request a slide.",
            "D-pad Down selects the batter-runner. Tap West or South just before first base.",
            "4 selects the batter-runner. Tap F or Space just before first base."),
        "T-R05" => new("Tag up after a catch", "Stay at the starting bag until the catch, then advance safely.",
            "A caught fly requires a retouch. Watch the catch before sending your runner to the next bag.",
            "Select with the D-pad. Wait for the catch, then point the stick toward the next bag.",
            "Select with 1/2/3. Wait for the catch, then use WASD toward the next bag."),
        "T-R06" => new("Time a steal", "Arm a steal and reach the next bag safely.",
            "Select the runner before the delivery. An early break during the pitcher's windup gives the runner a head start.",
            "D-pad selects the runner. Point toward the next bag or press L3 to arm the steal.",
            "1/2/3 selects the runner. Point with WASD or press Z to arm the steal."),
        "T-R07" => new("Steal home", "Send the runner from third and reach home safely.",
            "Home is a steal destination too. Watch the pitcher and commit before the catcher can make the play.",
            "D-pad Left selects third. Point the stick down toward home or press L3.",
            "3 selects the runner on third. Press S toward home or Z to arm the steal."),
        "T-R08" => new("Catch a stealing runner", "Throw from the catcher to retire the stealing runner.",
            "The runner breaks during the pitch. Once the catcher has the ball, select the runner's destination and throw.",
            "D-pad selects the destination bag. South makes the catcher's throw.",
            "1/2/3 selects the destination bag. Space makes the catcher's throw."),
        "T-D01" => new("Make a force out", "Throw to the forced runner's destination before they arrive.",
            "A forced runner must advance. The receiver can get the out by holding the ball on that bag.",
            "D-pad selects the force bag. South throws after you collect the ball.",
            "1/2/3/4 selects the force bag. Space throws after you collect the ball."),
        "T-D03" => new("Choose the lead out", "Throw to second to retire the lead runner while the batter reaches first.",
            "A runner starts on first. Choose second for the force out. The batter may reach first while you retire the lead runner.",
            "D-pad Up selects second. Collect the grounder and throw with South.",
            "2 selects second. Collect the grounder and throw with Space."),
        "T-D04" => new("Double off a runner", "Catch the ball, then throw back before the runner can retouch.",
            "The runner left before the catch. Return the ball to the starting bag for the second out.",
            "Catch the fly. D-pad selects the runner's starting bag; South throws back.",
            "Catch the fly. Select the runner's starting bag with 1/2/3; Space throws back."),
        "T-D05" => new("Tag a runner", "Hold the ball and touch the runner while they are off a bag.",
            "This runner is not forced. Merely reaching a bag with the ball does not retire them; your glove must reach the runner.",
            "Collect the ball. Steer the glove into the runner between the bags.",
            "Collect the ball. Use WASD to move the glove into the runner between the bags."),
        "T-D06" => new("Win a close play", "Commit to the close play and win the contest at the bag.",
            "A tight tag at third or home can become a close play. Watch the bag and respond when the contest starts.",
            "Tap South as the close play begins, then keep tapping through the contest.",
            "Tap Space as the close play begins, then keep tapping through the contest."),
        "T-D07" => new("Prevent a run with the third out", "Make the inning's final force out before the play ends.",
            "There are two outs. A third out on a force prevents runs from this play from counting.",
            "Select the force bag with the D-pad. Collect the ball and throw with South.",
            "Select the force bag with 1/2/3/4. Collect the ball and throw with Space."),
        "T-D08" => new("Turn a triple play", "Complete three outs in one live play.",
            "Read the runners and keep the ball moving. Each out must happen before its runner reaches safety.",
            "Select each target with the D-pad and throw with South after each handoff.",
            "Select each target with 1/2/3/4 and throw with Space after each handoff."),
        _ => null
    };
}
